name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust based on your needs (3.8+ works)

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Cache SentenceTransformer models
      - name: Cache SentenceTransformer models
        uses: actions/cache@v3
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-huggingface-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-huggingface-

      # Copy sample data files (assuming they're in the repo)
      - name: Prepare sample data
        run: |
          mkdir -p content
          cp telecom.csv content/telecom.csv
          cp "Error Codes.pdf" "content/Error Codes.pdf"

      # Run tests
      - name: Test Chatbot
        #env:
          #OPENAI_API_KEY: ${{ secrets.secfve }}  # Store your API key in GitHub Secrets
        run: |
          python chatbot.py <<EOF
          what is error code 002?
          exit
          EOF

      # Optional: Lint code (if you want to enforce style)
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=120 --exclude=venv